Update setup

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -166,19 +166,24 @@ WRAPPER_DST="$BIN_DIR/$TOOL_NAME"
 
 # Create wrapper content in variables for easy management
 CREATE_WRAPPER="${SHEBANG_PATH}
+
 PROJECT_DIR=\"$INSTALL_DIR\"
 cd \"\$PROJECT_DIR\" || { echo \"[x] ERROR: Failed to access project directory.\"; exit 1; }
 
-# Update storm
-if [ \"\$1\" == \"--update\" ]; then
+if [ \"\$1\" == \"--update\" ] && [ \$# -eq 1 ]; then
     exec ./smfupdate
-# Emergency
-elif [ ! -f \"./storm\" ]; then
-    echo \"[!] Storm core not found! Performing emergency repairs\"
-    exec ./smfupdate
+
+elif [ \$# -eq 0 ]; then
+
+    if [ ! -f \"./storm\" ]; then
+        exec ./smfupdate
+    else
+        exec ./storm
+    fi
+
 else
-    # Run storm
-    exec ./storm \"\$@\"
+    echo \"[x] Error: Command '\$@' not found.\"
+    exit 1
 fi"
 
 write_to_file "$CREATE_WRAPPER" "$WRAPPER_DST" false
